baseURL = "https://barcode91.github.io"
title   = "Cyber Security Blog"
languageCode = "tr"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "site"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false

disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Barcode"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]

  homeSubtitle = "Cyber Security Blog"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["/css/scroll.css"]
  customJS  = ["/js/scroll.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .post-content.

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = " root@Barcode#"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#808080" # 67a2c9
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Uncomment this if you want a portrait on your start page
   [params.portrait]
     path     = "/img/image.jpg"
     alt      = "Portrait"
     maxWidth = "50px"

  # Social icons
   [[params.social]]
    name = "email"
    url  = "mailto:mhmt.aktas91@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Barcode91"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mehmet-a-5aaaa717b/"

  



[languages]
  [languages.en]
    subtitle  = "Welcome the My Blog"
    weight    = 2
    

  [languages.tr]
    subtitle  = "Bloguma Hoşgeldiniz"
    weight    = 1
    

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
 

  [[menu.main]]
    identifier = "write-up"
    name       = "Write-up"
    url        = "categories/write-up/"
    weight     = 1 

  [[menu.main]]
    identifier = "Cyber Security"
    name       = "Cyber Security"
    url        = "categories/cyber-security/"
    weight     = 1

  [[menu.main]]
    identifier = "Network"
    name       = "Network"
    url        = "categories/network/"
    weight     = 1    

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"  

    [[menu.main]]
    identifier = "categories"
    name       = "Categories"
    url        = "categories/"


